import sys
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtCore import pyqtSlot, QObject
from PyQt5.QtWidgets import QAction

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(538, 368)
        font = QtGui.QFont()
        font.setFamily("Kalinga")
        font.setPointSize(9)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 521, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 181, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 141, 16))
        self.label_2.setObjectName("label_2")
        self.SelectPath = QtWidgets.QPushButton(self.groupBox)
        self.SelectPath.setGeometry(QtCore.QRect(50, 80, 75, 23))
        self.SelectPath.setObjectName("SelectPath")
        self.SelectedPath = QtWidgets.QLabel(self.groupBox)
        self.SelectedPath.setGeometry(QtCore.QRect(10, 40, 161, 41))
        self.SelectedPath.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SelectedPath.setWordWrap(True)
        self.SelectedPath.setObjectName("SelectedPath")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(215, 80, 121, 16))
        self.label_3.setObjectName("label_3")
        self.ReturnCode = QtWidgets.QLineEdit(self.centralwidget)
        self.ReturnCode.setGeometry(QtCore.QRect(340, 78, 191, 20))
        self.ReturnCode.setObjectName("ReturnCode")
        self.DontBlock = QtWidgets.QListWidget(self.centralwidget)
        self.DontBlock.setGeometry(QtCore.QRect(10, 200, 181, 131))
        self.DontBlock.setObjectName("DontBlock")
        self.AddProcess = QtWidgets.QPushButton(self.centralwidget)
        self.AddProcess.setGeometry(QtCore.QRect(4, 340, 91, 23))
        self.AddProcess.setObjectName("AddProcess")
        self.RemoveProcess = QtWidgets.QPushButton(self.centralwidget)
        self.RemoveProcess.setGeometry(QtCore.QRect(104, 340, 91, 23))
        self.RemoveProcess.setObjectName("RemoveProcess")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 184, 171, 16))
        self.label_4.setObjectName("label_4")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(200, 80, 20, 281))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(220, 100, 301, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.bsoff = QtWidgets.QRadioButton(self.groupBox_2)
        self.bsoff.setGeometry(QtCore.QRect(10, 20, 41, 17))
        self.bsoff.setChecked(True)
        self.bsoff.setObjectName("bsoff")
        self.bs7 = QtWidgets.QRadioButton(self.groupBox_2)
        self.bs7.setGeometry(QtCore.QRect(60, 20, 91, 17))
        self.bs7.setObjectName("bs7")
        self.bs8 = QtWidgets.QRadioButton(self.groupBox_2)
        self.bs8.setGeometry(QtCore.QRect(160, 20, 111, 17))
        self.bs8.setObjectName("bs8")
        self.bs10 = QtWidgets.QRadioButton(self.groupBox_2)
        self.bs10.setGeometry(QtCore.QRect(90, 40, 91, 17))
        self.bs10.setObjectName("bs10")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 281, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(220, 200, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(220, 220, 311, 71))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(74, 74, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(74, 74, 74))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_7.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_7.setLineWidth(-3)
        self.label_7.setMidLineWidth(-3)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_7.setWordWrap(True)
        self.label_7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_7.setObjectName("label_7")
        self.NiceModeTime = QtWidgets.QSpinBox(self.centralwidget)
        self.NiceModeTime.setGeometry(QtCore.QRect(316, 197, 211, 22))
        self.NiceModeTime.setMaximum(69)
        self.NiceModeTime.setObjectName("NiceModeTime")
        self.check1 = QtWidgets.QCheckBox(self.centralwidget)
        self.check1.setGeometry(QtCore.QRect(220, 290, 311, 17))
        font = QtGui.QFont()
        font.setFamily("Kalinga")
        font.setPointSize(8)
        self.check1.setFont(font)
        self.check1.setObjectName("check1")
        self.check2 = QtWidgets.QCheckBox(self.centralwidget)
        self.check2.setGeometry(QtCore.QRect(220, 310, 311, 17))
        font = QtGui.QFont()
        font.setFamily("Kalinga")
        font.setPointSize(8)
        self.check2.setFont(font)
        self.check2.setObjectName("check2")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setEnabled(False)
        self.generate.setGeometry(QtCore.QRect(280, 330, 181, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(47, 250, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(47, 250, 1))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.generate.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.generate.setFont(font)
        self.generate.setCheckable(False)
        self.generate.setObjectName("generate")
        self.jujruwjer923rrj3943493403 = QtWidgets.QLabel(self.centralwidget)
        self.jujruwjer923rrj3943493403.setGeometry(QtCore.QRect(473, 7, 61, 16))
        self.jujruwjer923rrj3943493403.setObjectName("jujruwjer923rrj3943493403")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(240, 0, 61, 51))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("icon.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.SelectPath.clicked.connect(selectpath)
        self.AddProcess.clicked.connect(addproc)
        self.RemoveProcess.clicked.connect(removeproc)
        self.generate.clicked.connect(generate)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BlueUSB Generator"))
        self.label.setText(_translate("MainWindow", "BlueUSB Generator"))
        self.groupBox.setTitle(_translate("MainWindow", "Path"))
        self.label_2.setText(_translate("MainWindow", "Currently selected path:"))
        self.SelectPath.setText(_translate("MainWindow", "Select path"))
        self.SelectedPath.setText(_translate("MainWindow", "None"))
        self.label_3.setText(_translate("MainWindow", "Return code (Win10):"))
        self.ReturnCode.setText(_translate("MainWindow", "Couldn\'t bind to remote port"))
        self.AddProcess.setText(_translate("MainWindow", "Add process"))
        self.RemoveProcess.setText(_translate("MainWindow", "Remove proc"))
        self.label_4.setText(_translate("MainWindow", "Don\'t block these processes:"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Force a specific Windows Bluescreen:"))
        self.bsoff.setText(_translate("MainWindow", "Off"))
        self.bs7.setText(_translate("MainWindow", "Windows 7"))
        self.bs8.setText(_translate("MainWindow", "Windows 8/8.1"))
        self.bs10.setText(_translate("MainWindow", "Windows 10"))
        self.label_5.setText(_translate("MainWindow", "If it\'s off, it will bluescreen with the correct version of Windows."))
        self.label_6.setText(_translate("MainWindow", "Nice mode time:"))
        self.label_7.setText(_translate("MainWindow", "Nice mode will stop the bluescreen after the selected time. Set to 0 to disable \"Nice mode\". Setting the value to 1 or more will cause processes to not be suspended."))
        self.NiceModeTime.setSuffix(_translate("MainWindow", " seconds"))
        self.check1.setText(_translate("MainWindow", "I understand I\'ll be responsible for any damages"))
        self.check2.setText(_translate("MainWindow", "I have read & agreed to the license"))
        self.generate.setText(_translate("MainWindow", "Generate!"))
        self.jujruwjer923rrj3943493403.setText(_translate("MainWindow", "By Cyclip"))

@QtCore.pyqtSlot()
def selectpath():
    pass

@QtCore.pyqtSlot()
def addproc():
    pass

@QtCore.pyqtSlot()
def removeproc():
    pass

@QtCore.pyqtSlot()
def generate():
    pass


import sys
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())

